#!/bin/bash -l
module purge
module use /apps/ops/test/nco/modulefiles
module load craype-x86-rome 
module load libfabric/1.11.0.0. 
module load craype-network-ofi 
module load envvar/1.0
module load core/rocoto/1.3.5

cyctime=202212151200
#rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c all

test=11

case $test in
11)
taskname=get_extrn_lbcs
;;
12)
taskname=make_ics
;;
13)
taskname=make_lbcs
;;
14)
taskname=get_extrn_ics
;;
21)
taskname=prep_cyc_spinup
;;
22)
taskname=anal_gsi_input_spinup
;;
220)
taskname=postanal_input_spinup
;;
23)
taskname=run_fcst_spinup
;;
24)
taskname=run_post_spinup_f001
;;
240)
taskname=run_wgrib2_spinup_f001
;;
25)
taskname=cldanl_nonvar_spinup
;;
26)
taskname=process_radarref_spinup
;;
27)
taskname=process_bufr_spinup
;;
28)
taskname=hybrid_radar_ref_spinup
;;
31)
taskname=prep_cyc_prod
;;
32)
taskname=anal_gsi_input_prod
;;
33)
taskname=run_fcst_prod
;;
34)
taskname=run_post_f012
;;
35)
taskname=cldanl_nonvar_prod
;;
350)
taskname=run_wgrib2_f020
;;
36)
taskname=process_radarref_prod
;;
37)
taskname=process_bufr_prod
;;
38)
taskname=hybrid_radar_ref_prod
;;
39)
taskname=save_restart_prod_f1
;;
390)
taskname=process_smoke_prod
;;
41)
taskname=run_clean
;;
esac

echo $taskname


rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t $taskname
rocotorewind -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t $taskname
rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t $taskname
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -m $taskname

#rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t anal_gsi_input_prod
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t anal_gsi_input_prod
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t prep_start_f000
#rocotocomplete -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t anal_gsi_input_f000
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t prep_start_f000
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t run_fcst_f000
exit
#rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105180000 -t get_extrn_lbcs
rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105180000 -t get_extrn_ics
rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105180000 -t get_extrn_ics
#rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105180000 -t prep_coldstart

#rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c all
#rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105140300 -t anal_gsi_input
#rocotostat -w /gpfs/dell2/emc/modeling/noscrub/Ming.Hu/rrfs/RRFS_dev2/FV3LAM_wflow.xml -d /gpfs/dell2/emc/modeling/noscrub/Ming.Hu/rrfs/RRFS_dev2/FV3LAM_wflow.db -c all
