#!/bin/bash

#rm -f /lfs/h2/emc/ptmp/emc.lam/rrfs/v0.3.8
#ln -sf  /lfs/h2/emc/ptmp/emc.lam/rrfs/v0.3.8_cactus /lfs/h2/emc/ptmp/emc.lam/rrfs/v0.3.8

conus_ver=v0.5.2
na_ver=v0.7.9
exp_ver=v0.8.3

mysite=$(cat /etc/cluster_name)
primary=$(head -1 /lfs/h1/ops/prod/config/prodmachinefile | cut -d ":" -f2-)
backup=$(head -2 /lfs/h1/ops/prod/config/prodmachinefile | tail -1 | cut -d ":" -f2-)

if [ "$primary" == "$mysite" ]; then
  machine=prod
  echo "this prod machine"
else
  machine=dev
  echo "this develop machine"
fi

#link to t2o dir
#since na prod is in h2 disk, link prod to f2/t2o disk first

rm -f /lfs/h2/emc/ptmp/emc.lam/rrfs/na
rm -f /lfs/f2/t2o/ptmp/emc/ptmp/emc.lam/rrfs/na

if [ "$machine" == "prod" ]; then
# ln -sf /lfs/f2/t2o/ptmp/emc/ptmp/emc.lam/rrfs/${na_ver} /lfs/h2/emc/ptmp/emc.lam/rrfs/na
ln -sf /lfs/h2/emc/ptmp/emc.lam/rrfs/${na_ver} /lfs/h2/emc/ptmp/emc.lam/rrfs/na
ln -sf /lfs/f2/t2o/ptmp/emc/ptmp/emc.lam/rrfs/${na_ver} /lfs/f2/t2o/ptmp/emc/ptmp/emc.lam/rrfs/na
else
ln -sf /lfs/h2/emc/ptmp/emc.lam/rrfs/${na_ver} /lfs/h2/emc/ptmp/emc.lam/rrfs/na
ln -sf /lfs/h2/emc/ptmp/emc.lam/rrfs/${exp_ver} /lfs/h2/emc/ptmp/emc.lam/rrfs/exp
fi

exit
