#!/bin/bash -l

#set -x
module use /apps/ops/test/nco/modulefiles
module load craype-x86-rome
module load libfabric/1.11.0.0.
module load craype-network-ofi
module load envvar/1.0
module load core/rocoto/1.3.5

cyctime=202212021900
#rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c all

taskname=anal_gsi_input_prod
taskname=run_fcst_prod

taskname=run_fcst_spinup
taskname=make_ics
taskname=run_clean
taskname=make_lbcs
taskname=get_extrn_lbcs
taskname=run_wgrib2_spinup_f000
taskname=get_extrn_lbcs
taskname=prep_cyc_spinup
taskname=anal_gsi_input_spinup
taskname=prep_cyc_prod
taskname=anal_gsi_input_prod
taskname=run_fcst_prod
taskname=get_extrn_ics
taskname=anal_gsi_input_prod
taskname=get_extrn_lbcs_mem0001
taskname=run_fcst_prod_mem0004
taskname=run_recenter_ensinit
taskname=prep_cyc_ensmean
taskname=prep_cyc_prod_mem0023
taskname=observer_gsi_ensmean


rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t $taskname
exit



rocotorewind -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t $taskname
rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t $taskname

#rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t anal_gsi_input_prod
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t anal_gsi_input_prod
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t prep_start_f000
#rocotocomplete -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t anal_gsi_input_f000
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t prep_start_f000
#rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c $cyctime -t run_fcst_f000
exit
#rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105180000 -t get_extrn_lbcs
rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105180000 -t get_extrn_ics
rocotoboot -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105180000 -t get_extrn_ics
#rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105180000 -t prep_coldstart

#rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c all
#rocotocheck -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c 202105140300 -t anal_gsi_input
#rocotostat -w /gpfs/dell2/emc/modeling/noscrub/Ming.Hu/rrfs/RRFS_dev2/FV3LAM_wflow.xml -d /gpfs/dell2/emc/modeling/noscrub/Ming.Hu/rrfs/RRFS_dev2/FV3LAM_wflow.db -c all
